/**
 * Client-safe ActivityType enum
 * This is a copy of the ActivityType enum from Prisma schema
 * to avoid importing Prisma types in client components
 */
export enum ActivityType {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_ROLE_CHANGED = "USER_ROLE_CHANGED",
  USER_BANNED = "USER_BANNED",
  USER_UNBANNED = "USER_UNBANNED",
  USER_IMPERSONATED = "USER_IMPERSONATED",
  INVITE_CREATED = "INVITE_CREATED",
  INVITE_DELETED = "INVITE_DELETED",
  GIG_CREATED = "GIG_CREATED",
  GIG_UPDATED = "GIG_UPDATED",
  GIG_DELETED = "GIG_DELETED",
  CONTENT_CREATED = "CONTENT_CREATED",
  CONTENT_UPDATED = "CONTENT_UPDATED",
  CONTENT_DELETED = "CONTENT_DELETED",
  CREW_MEMBER_CREATED = "CREW_MEMBER_CREATED",
  CREW_MEMBER_UPDATED = "CREW_MEMBER_UPDATED",
  CREW_MEMBER_DELETED = "CREW_MEMBER_DELETED",
  FILE_UPLOADED = "FILE_UPLOADED",
  FILE_DELETED = "FILE_DELETED",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  OTHER = "OTHER",
}
