/**
 * Client-safe copy of the `ActivityType` enum from `prisma/schema.prisma`, so
 * client components can filter and label activity without pulling in the Prisma
 * client.
 *
 * Kept in sync by hand. `activityTypeLabel` derives its text from the member
 * name rather than a lookup table, so a value added to the schema and copied
 * here reads correctly without a second edit.
 */
export enum ActivityType {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  INVITE_CREATED = "INVITE_CREATED",
  INVITE_DELETED = "INVITE_DELETED",
  GIG_CREATED = "GIG_CREATED",
  GIG_UPDATED = "GIG_UPDATED",
  GIG_DELETED = "GIG_DELETED",
  CONTENT_CREATED = "CONTENT_CREATED",
  CONTENT_UPDATED = "CONTENT_UPDATED",
  CONTENT_DELETED = "CONTENT_DELETED",
  CREW_MEMBER_CREATED = "CREW_MEMBER_CREATED",
  CREW_MEMBER_UPDATED = "CREW_MEMBER_UPDATED",
  CREW_MEMBER_DELETED = "CREW_MEMBER_DELETED",
  CREW_MEMBER_PROFILE_LINKED = "CREW_MEMBER_PROFILE_LINKED",
  CREW_MEMBER_PROFILE_UNLINKED = "CREW_MEMBER_PROFILE_UNLINKED",
  GEAR_CREATED = "GEAR_CREATED",
  GEAR_UPDATED = "GEAR_UPDATED",
  GEAR_DELETED = "GEAR_DELETED",
  PACKAGE_CREATED = "PACKAGE_CREATED",
  PACKAGE_UPDATED = "PACKAGE_UPDATED",
  PACKAGE_DELETED = "PACKAGE_DELETED",
  RENTAL_CREATED = "RENTAL_CREATED",
  RENTAL_UPDATED = "RENTAL_UPDATED",
  RENTAL_DELETED = "RENTAL_DELETED",
  RENTAL_APPROVED = "RENTAL_APPROVED",
  RENTAL_REJECTED = "RENTAL_REJECTED",
  DISCOUNT_RULE_CREATED = "DISCOUNT_RULE_CREATED",
  DISCOUNT_RULE_UPDATED = "DISCOUNT_RULE_UPDATED",
  DISCOUNT_RULE_DELETED = "DISCOUNT_RULE_DELETED",
  FILE_UPLOADED = "FILE_UPLOADED",
  FILE_DELETED = "FILE_DELETED",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  USER_PERMISSION_CHANGED = "USER_PERMISSION_CHANGED",
  USER_PERMISSION_ADDED = "USER_PERMISSION_ADDED",
  USER_PERMISSION_REMOVED = "USER_PERMISSION_REMOVED",
  CREATOR_PROFILE_CREATED = "CREATOR_PROFILE_CREATED",
  CREATOR_PROFILE_UPDATED = "CREATOR_PROFILE_UPDATED",
  CREATOR_PROFILE_PUBLISHED = "CREATOR_PROFILE_PUBLISHED",
  CREATOR_PROFILE_UNPUBLISHED = "CREATOR_PROFILE_UNPUBLISHED",
  CREATOR_PROFILE_DELETED = "CREATOR_PROFILE_DELETED",
  CREATOR_PROFILE_LINKED = "CREATOR_PROFILE_LINKED",
  CREATOR_PROFILE_UNLINKED = "CREATOR_PROFILE_UNLINKED",
  CREATOR_BLOCK_CREATED = "CREATOR_BLOCK_CREATED",
  CREATOR_BLOCK_UPDATED = "CREATOR_BLOCK_UPDATED",
  CREATOR_BLOCK_DELETED = "CREATOR_BLOCK_DELETED",
  CREATOR_CLAIM_REQUESTED = "CREATOR_CLAIM_REQUESTED",
  CREATOR_CLAIM_APPROVED = "CREATOR_CLAIM_APPROVED",
  CREATOR_CLAIM_REJECTED = "CREATOR_CLAIM_REJECTED",
  CREATOR_THEME_CREATED = "CREATOR_THEME_CREATED",
  CREATOR_THEME_UPDATED = "CREATOR_THEME_UPDATED",
  CREATOR_THEME_DELETED = "CREATOR_THEME_DELETED",
  CREATOR_THEME_PUBLISHED = "CREATOR_THEME_PUBLISHED",
  CREATOR_THEME_UNPUBLISHED = "CREATOR_THEME_UNPUBLISHED",
  CREATOR_THEME_DUPLICATED = "CREATOR_THEME_DUPLICATED",
  GIG_CREATOR_ADDED = "GIG_CREATOR_ADDED",
  GIG_CREATOR_REMOVED = "GIG_CREATOR_REMOVED",
  TICKET_EVENT_CREATED = "TICKET_EVENT_CREATED",
  TICKET_EVENT_UPDATED = "TICKET_EVENT_UPDATED",
  TICKET_EVENT_DELETED = "TICKET_EVENT_DELETED",
  TICKET_EVENT_PUBLISHED = "TICKET_EVENT_PUBLISHED",
  TICKET_EVENT_CANCELLED = "TICKET_EVENT_CANCELLED",
  TICKET_TIER_CREATED = "TICKET_TIER_CREATED",
  TICKET_TIER_UPDATED = "TICKET_TIER_UPDATED",
  TICKET_TIER_DELETED = "TICKET_TIER_DELETED",
  TICKET_ORDER_PAID = "TICKET_ORDER_PAID",
  TICKET_ORDER_REFUNDED = "TICKET_ORDER_REFUNDED",
  TICKET_ISSUED = "TICKET_ISSUED",
  TICKET_VOIDED = "TICKET_VOIDED",
  TICKET_DELETED = "TICKET_DELETED",
  TICKET_RESENT = "TICKET_RESENT",
  TICKET_SCANNED = "TICKET_SCANNED",
  TICKET_SCAN_OVERRIDE = "TICKET_SCAN_OVERRIDE",
  TICKET_ENTRY_DENIED = "TICKET_ENTRY_DENIED",
  TICKET_ACCESS_CHANGED = "TICKET_ACCESS_CHANGED",
  TICKET_COMPED = "TICKET_COMPED",
  TICKET_HANDOUT_SENT = "TICKET_HANDOUT_SENT",
  TICKET_LINK_BATCH_CREATED = "TICKET_LINK_BATCH_CREATED",
  DISCOUNT_CODE_CREATED = "DISCOUNT_CODE_CREATED",
  DISCOUNT_CODE_UPDATED = "DISCOUNT_CODE_UPDATED",
  DISCOUNT_CODE_DELETED = "DISCOUNT_CODE_DELETED",
  DOOR_STAFF_ASSIGNED = "DOOR_STAFF_ASSIGNED",
  DOOR_STAFF_REMOVED = "DOOR_STAFF_REMOVED",
  BOX_OFFICE_SALE = "BOX_OFFICE_SALE",
  PATRON_BANNED = "PATRON_BANNED",
  PATRON_BAN_LIFTED = "PATRON_BAN_LIFTED",
  PATRON_PURGED = "PATRON_PURGED",
  OTHER = "OTHER",
}

/** Every member, for filter dropdowns. */
export const ACTIVITY_TYPE_VALUES = Object.values(ActivityType);

/** Words that should keep their casing when a member name is turned into a label. */
const KEEP_UPPERCASE = new Set(["ID", "GST", "AAA"]);

/**
 * "TICKET_SCAN_OVERRIDE" -> "Ticket scan override".
 *
 * Sentence case, matching the rest of the admin, and derived rather than looked
 * up so a new schema value is readable the moment it is copied across.
 */
export function activityTypeLabel(type: string): string {
  const words = type.split("_");
  return words
    .map((word, index) => {
      if (KEEP_UPPERCASE.has(word)) return word;
      const lower = word.toLowerCase();
      return index === 0
        ? lower.charAt(0).toUpperCase() + lower.slice(1)
        : lower;
    })
    .join(" ");
}

export type ActivityTone = "created" | "updated" | "removed" | "neutral";

/**
 * What kind of thing happened, from the verb at the end of the member name.
 * Drives badge colour, so "…_DELETED" reads as destructive everywhere without a
 * per-value table that goes stale.
 */
export function activityTypeTone(type: string): ActivityTone {
  if (
    /_(DELETED|REMOVED|REJECTED|VOIDED|CANCELLED|DENIED|PURGED|BANNED)$/.test(
      type,
    )
  ) {
    return "removed";
  }
  if (
    /_(CREATED|ADDED|ISSUED|PAID|APPROVED|PUBLISHED|SENT|ASSIGNED|COMPED|REQUESTED|DUPLICATED)$/.test(
      type,
    )
  ) {
    return "created";
  }
  if (
    /_(UPDATED|CHANGED|UNPUBLISHED|LIFTED|RESENT|SCANNED|REFUNDED|OVERRIDE|LINKED|UNLINKED)$/.test(
      type,
    )
  ) {
    return "updated";
  }
  return "neutral";
}
