import ExpoModulesCore
import UIKit
import Vision

/**
 Reading an ID document on the handset.

 Apple's Vision framework does the optical work: it is on every iPhone, it is
 free, it runs offline in a couple of hundred milliseconds, and — the reason it
 was chosen over any of the paid SDKs or a server round trip — **the photograph
 of somebody's licence never leaves the phone.** What crosses the network is a
 list of text lines and, if the door captured one, a cropped portrait. The
 address, the licence classes and everything else printed on the card are gone
 before anything is sent.

 What comes back is deliberately raw. Turning `3. 15 JAN 1990` into a date of
 birth happens on the server, in `~/lib/ticketing/id-documents.ts`, so that the
 phone and the web door can never disagree about what a date means and so that
 a new card design can be handled with a deploy instead of an App Store review.

 This is a local Expo module rather than anything written into `ios/` by hand,
 for the same reason the Tap to Pay education module next door is: `ios/` is
 generated by `expo prebuild` and gitignored, so a patch applied there is
 destroyed by the next build.
 */
public class TextRecognitionModule: Module {
  public func definition() -> ModuleDefinition {
    Name("TextRecognition")

    /// Vision has shipped since iOS 13 and the app's floor is above that, so
    /// this is really "are we on Apple". The JS side still asks, because the
    /// answer decides whether the door offers ID scanning or hides it.
    Function("isAvailable") { () -> Bool in
      true
    }

    /**
     Recognise the text on a captured document, and crop the portrait from it.

     Runs off the main thread: `.accurate` recognition takes long enough that
     doing it inline drops the camera preview, and a door notices.
     */
    AsyncFunction("readDocument") { (uri: String, promise: Promise) in
      guard let cgImage = Self.loadUprightImage(uri) else {
        promise.reject("ERR_ID_OCR_IMAGE", "That photo could not be opened.")
        return
      }

      DispatchQueue.global(qos: .userInitiated).async {
        let text = VNRecognizeTextRequest()
        // Slower than `.fast` and worth every millisecond: `.fast` reads a
        // licence number as a smear.
        text.recognitionLevel = .accurate
        // Off, and this matters more than anything else here. Language
        // correction "fixes" surnames into dictionary words and turns
        // `AB123456` into something that was never on the card.
        text.usesLanguageCorrection = false
        text.recognitionLanguages = ["en-US"]

        let faces = VNDetectFaceRectanglesRequest()

        do {
          // `.up`: the image was already normalised on the way in, so telling
          // Vision anything else would rotate it a second time.
          let handler = VNImageRequestHandler(
            cgImage: cgImage,
            orientation: .up,
            options: [:]
          )
          try handler.perform([text, faces])
        } catch {
          promise.reject("ERR_ID_OCR_FAILED", error.localizedDescription)
          return
        }

        let observations = (text.results ?? [])
          // Reading order. Vision's normalised space has its origin at the
          // bottom left, so descending `y` is top-to-bottom on the card — which
          // is what lets the server's templates rely on the surname appearing
          // above the given names.
          .sorted { first, second in
            let dy = first.boundingBox.origin.y - second.boundingBox.origin.y
            if abs(dy) > 0.02 { return dy > 0 }
            return first.boundingBox.origin.x < second.boundingBox.origin.x
          }

        let lines: [[String: Any]] = observations.compactMap { observation in
          guard let candidate = observation.topCandidates(1).first else {
            return nil
          }
          return [
            "text": candidate.string,
            "confidence": candidate.confidence,
            "x": observation.boundingBox.origin.x,
            "y": observation.boundingBox.origin.y,
            "width": observation.boundingBox.size.width,
            "height": observation.boundingBox.size.height,
          ]
        }

        let portrait = Self.portrait(
          from: cgImage,
          faces: faces.results ?? []
        )

        promise.resolve([
          "lines": lines,
          "portrait": portrait as Any,
        ])
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Images
  // ---------------------------------------------------------------------------

  /**
   Load a captured photo with its rotation already applied.

   A photo off the back camera carries an orientation flag rather than rotated
   pixels, and Vision reads the pixels. Redrawing it upright once here is what
   stops a card held normally being recognised sideways — where the text is
   found but every line comes back as gibberish.
   */
  private static func loadUprightImage(_ uri: String) -> CGImage? {
    let path = uri.hasPrefix("file://") ? String(uri.dropFirst(7)) : uri
    guard
      let raw = UIImage(contentsOfFile: path.removingPercentEncoding ?? path)
    else {
      return nil
    }

    if raw.imageOrientation == .up {
      return raw.cgImage
    }

    let format = UIGraphicsImageRendererFormat.default()
    format.scale = 1
    let renderer = UIGraphicsImageRenderer(size: raw.size, format: format)
    let upright = renderer.image { _ in
      raw.draw(in: CGRect(origin: .zero, size: raw.size))
    }
    return upright.cgImage
  }

  /// Portraits are shown on a phone and stored for a while; full resolution is
  /// nobody's friend here.
  private static let portraitMaxEdge: CGFloat = 480

  /**
   Crop the face out of the card, as JPEG base64.

   Only the face. Storing the whole document would mean keeping an address and a
   licence number we have no use for, so the crop happens here — before anything
   is uploaded — rather than being trimmed later on a server that would have had
   to receive it first.

   Padded well past the detected rectangle: Vision returns a tight box around
   the features, and a portrait cropped to it is a disconcerting thing to put in
   front of door staff who are trying to match it to a face.
   */
  private static func portrait(
    from image: CGImage,
    faces: [VNFaceObservation]
  ) -> String? {
    // The biggest face on the card is the cardholder. Anything else Vision
    // found is a watermark or a ghost image.
    guard
      let face = faces.max(by: {
        $0.boundingBox.width * $0.boundingBox.height
          < $1.boundingBox.width * $1.boundingBox.height
      })
    else {
      return nil
    }

    let width = CGFloat(image.width)
    let height = CGFloat(image.height)
    let box = face.boundingBox

    // Vision's origin is bottom-left and Core Graphics' is top-left, so the
    // y axis is flipped on the way across.
    var rect = CGRect(
      x: box.origin.x * width,
      y: (1 - box.origin.y - box.size.height) * height,
      width: box.size.width * width,
      height: box.size.height * height
    )

    let padX = rect.width * 0.45
    let padY = rect.height * 0.45
    rect = rect.insetBy(dx: -padX, dy: -padY)
    rect = rect.intersection(CGRect(x: 0, y: 0, width: width, height: height))
    guard !rect.isNull, rect.width > 40, rect.height > 40 else { return nil }

    guard let cropped = image.cropping(to: rect) else { return nil }

    let scale = min(
      1,
      portraitMaxEdge / max(CGFloat(cropped.width), CGFloat(cropped.height))
    )
    let size = CGSize(
      width: CGFloat(cropped.width) * scale,
      height: CGFloat(cropped.height) * scale
    )

    let format = UIGraphicsImageRendererFormat.default()
    format.scale = 1
    let rendered = UIGraphicsImageRenderer(size: size, format: format).image {
      _ in
      UIImage(cgImage: cropped).draw(in: CGRect(origin: .zero, size: size))
    }

    return rendered.jpegData(compressionQuality: 0.7)?.base64EncodedString()
  }
}
