import ExpoModulesCore
import ProximityReader
import UIKit

/**
 Apple's own Tap to Pay on iPhone merchant education, presented in-app.

 Apple's App Review checklist row 4.1 requires `ProximityReaderDiscovery` on
 iOS 18 and later, and satisfying it discharges rows 4.4, 4.6, 4.7 and 4.8 in
 one move — the content is written, localised and kept current by Apple for the
 merchant's own region, which is the whole reason they want it used instead of
 screens we draw ourselves.

 The Stripe Terminal React Native SDK does **not** expose this. Its iOS bridge
 touches `TapToPayDiscoveryConfiguration` only. No dependency is added by
 reaching for it directly: `ProximityReader` is a system framework that the
 Terminal SDK already links.

 This is a local Expo module rather than anything written into `ios/` by hand,
 because `ios/` is generated by `expo prebuild` and gitignored — a patch applied
 there is destroyed by the next build.
 */
public class ProximityEducationModule: Module {
  public func definition() -> ModuleDefinition {
    Name("ProximityEducation")

    /**
     Whether Apple can present its own education on this handset.

     False on iOS 17 and earlier, where the caller has to fall back to screens
     of our own — which is why the education screen in the app is not optional
     scaffolding around this call, but the required path for older iOS.
     */
    Function("isAvailable") { () -> Bool in
      if #available(iOS 18.0, *) {
        return true
      }
      return false
    }

    /**
     Present Apple's "How to Tap" content.

     Two details decide whether this works at all:

     - The `#available` guard. `ProximityReaderDiscovery` does not exist before
       iOS 18, and touching it there traps.
     - The topmost presented view controller. Apple presents onto whatever is
       handed over, so passing the root while a modal is up fails silently. The
       Atmos checkout runs inside a full-screen modal, which makes walking the
       `presentedViewController` chain the normal case here rather than an edge
       case.
     */
    AsyncFunction("presentHowToTap") { (promise: Promise) in
      guard #available(iOS 18.0, *) else {
        promise.reject(
          "ERR_PROXIMITY_EDUCATION_UNAVAILABLE",
          "Apple's Tap to Pay education needs iOS 18 or later."
        )
        return
      }

      DispatchQueue.main.async {
        guard let root = Self.topViewController() else {
          promise.reject(
            "ERR_PROXIMITY_EDUCATION_NO_VIEW",
            "No view controller was available to present from."
          )
          return
        }

        Task {
          do {
            let discovery = ProximityReaderDiscovery()
            let content = try await discovery.content(for: .payment(.howToTap))
            discovery.presentContent(content, from: root)
            promise.resolve(nil)
          } catch {
            promise.reject(
              "ERR_PROXIMITY_EDUCATION_FAILED",
              error.localizedDescription
            )
          }
        }
      }
    }
  }

  /// The controller actually on screen, not the one at the bottom of the stack.
  private static func topViewController() -> UIViewController? {
    let scene = UIApplication.shared.connectedScenes
      .compactMap { $0 as? UIWindowScene }
      .first { $0.activationState == .foregroundActive }
      ?? UIApplication.shared.connectedScenes
        .compactMap { $0 as? UIWindowScene }
        .first

    guard
      var top = scene?.windows.first(where: \.isKeyWindow)?.rootViewController
        ?? scene?.windows.first?.rootViewController
    else {
      return nil
    }

    while let presented = top.presentedViewController {
      top = presented
    }
    return top
  }
}
