-- Remove the superseded authorization model after explicit permissions have
-- been assigned and verified.

-- These audit rows describe authorization concepts that no longer exist.
DELETE FROM "activity_log"
WHERE "type"::text IN (
  'USER_ROLE_CHANGED',
  'USER_ROLE_ADDED',
  'USER_ROLE_REMOVED'
);

-- PostgreSQL enum values cannot be removed in place, so rebuild ActivityType
-- from the current Prisma schema without the removed authorization events.
BEGIN;
CREATE TYPE "ActivityType_new" AS ENUM (
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DELETED',
  'INVITE_CREATED',
  'INVITE_DELETED',
  'GIG_CREATED',
  'GIG_UPDATED',
  'GIG_DELETED',
  'CONTENT_CREATED',
  'CONTENT_UPDATED',
  'CONTENT_DELETED',
  'CREW_MEMBER_CREATED',
  'CREW_MEMBER_UPDATED',
  'CREW_MEMBER_DELETED',
  'CREW_MEMBER_PROFILE_LINKED',
  'CREW_MEMBER_PROFILE_UNLINKED',
  'GEAR_CREATED',
  'GEAR_UPDATED',
  'GEAR_DELETED',
  'PACKAGE_CREATED',
  'PACKAGE_UPDATED',
  'PACKAGE_DELETED',
  'RENTAL_CREATED',
  'RENTAL_UPDATED',
  'RENTAL_DELETED',
  'RENTAL_APPROVED',
  'RENTAL_REJECTED',
  'DISCOUNT_RULE_CREATED',
  'DISCOUNT_RULE_UPDATED',
  'DISCOUNT_RULE_DELETED',
  'FILE_UPLOADED',
  'FILE_DELETED',
  'LOGIN',
  'LOGOUT',
  'USER_PERMISSION_CHANGED',
  'USER_PERMISSION_ADDED',
  'USER_PERMISSION_REMOVED',
  'CREATOR_PROFILE_CREATED',
  'CREATOR_PROFILE_UPDATED',
  'CREATOR_PROFILE_PUBLISHED',
  'CREATOR_PROFILE_UNPUBLISHED',
  'CREATOR_PROFILE_DELETED',
  'CREATOR_PROFILE_LINKED',
  'CREATOR_PROFILE_UNLINKED',
  'CREATOR_BLOCK_CREATED',
  'CREATOR_BLOCK_UPDATED',
  'CREATOR_BLOCK_DELETED',
  'CREATOR_CLAIM_REQUESTED',
  'CREATOR_CLAIM_APPROVED',
  'CREATOR_CLAIM_REJECTED',
  'CREATOR_THEME_CREATED',
  'CREATOR_THEME_UPDATED',
  'CREATOR_THEME_DELETED',
  'CREATOR_THEME_PUBLISHED',
  'CREATOR_THEME_UNPUBLISHED',
  'CREATOR_THEME_DUPLICATED',
  'GIG_CREATOR_ADDED',
  'GIG_CREATOR_REMOVED',
  'TICKET_EVENT_CREATED',
  'TICKET_EVENT_UPDATED',
  'TICKET_EVENT_DELETED',
  'TICKET_EVENT_PUBLISHED',
  'TICKET_EVENT_CANCELLED',
  'TICKET_TIER_CREATED',
  'TICKET_TIER_UPDATED',
  'TICKET_TIER_DELETED',
  'TICKET_ORDER_PAID',
  'TICKET_ORDER_REFUNDED',
  'TICKET_ISSUED',
  'TICKET_VOIDED',
  'TICKET_RESENT',
  'TICKET_SCANNED',
  'TICKET_SCAN_OVERRIDE',
  'DISCOUNT_CODE_CREATED',
  'DISCOUNT_CODE_UPDATED',
  'DISCOUNT_CODE_DELETED',
  'DOOR_STAFF_ASSIGNED',
  'DOOR_STAFF_REMOVED',
  'BOX_OFFICE_SALE',
  'OTHER'
);
ALTER TABLE "activity_log"
ALTER COLUMN "type" TYPE "ActivityType_new"
USING ("type"::text::"ActivityType_new");
ALTER TYPE "ActivityType" RENAME TO "ActivityType_old";
ALTER TYPE "ActivityType_new" RENAME TO "ActivityType";
DROP TYPE "ActivityType_old";
COMMIT;

ALTER TABLE "invite" DROP COLUMN "role";

DROP TABLE "user_role_assignment";
DROP TYPE "UserRole";

DELETE FROM "key_value_store"
WHERE "key" = 'authorization.permissions.cutover';
